%{?scl:%scl_package nodejs-read-installed}
%{!?scl:%global pkg_name %{name}}
%{?nodejs_find_provides_and_requires}

Name:           %{?scl_prefix}nodejs-read-installed
Version:        4.0.3
Release:        2%{?dist}
Summary:        Returns a tree structure of all installed packages in a folder

License:        ISC
URL:            https://github.com/isaacs/read-installed
Source0:        http://registry.npmjs.org/read-installed/-/read-installed-%{version}.tgz
BuildRequires:  %{?scl_prefix}nodejs-devel
BuildArch:  noarch
%if 0%{?fedora} >= 19
ExclusiveArch: %{ix86} x86_64 %{arm} noarch
%else
ExclusiveArch: %{ix86} x86_64 %{arm} noarch
%endif

%description
Reads all the installed packages in a folder, and returns a tree structure with
all the data.

%prep
%setup -q -n package

%build
#nothing to do

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/read-installed
cp -pr package.json read-installed.js %{buildroot}%{nodejs_sitelib}/read-installed

%nodejs_symlink_deps


%files
%{nodejs_sitelib}/read-installed
%doc LICENSE README.md

%changelog
* Sun Feb 14 2016 Zuzana Svetlikova <zsvetlik@redhat.com> - 4.0.3-2
- rebuilt

* Mon Nov 30 2015 Tomas Hrcka <thrcka@redhat.com> - 4.0.3-1
- New upstream release

* Fri Jan 09 2015 Tomas Hrcka <thrcka@redhat.com> - 2.0.5-1
- New upstream release 2.0.5

* Thu Oct 17 2013 Tomas Hrcka <thrcka@redhat.com> - 0.2.4-2
- replace provides and requires with macro

* Sat Sep 07 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.2.4-1
- update to upstream release 0.2.4
- change License from BSD to ISC
- add ExclusiveArch logic

* Tue Jul 30 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.2.3-1
- new upstream release 0.2.3

* Sun Jun 23 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.2.2-1
- new upstream release 0.2.2

* Sat Jun 22 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.1.1-3
- restrict to compatible arches

* Mon Apr 15 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.1.1-2
- add macro for EPEL6 dependency generation

* Fri Apr 12 2013 Stanislav Ochotnicky <sochotnicky@redhat.com> - 0.1.1-2
- Add support for software collections

* Sat Feb 09 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.1.1-1
- new upstream release 0.1.1

* Tue Jan 08 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.4-2
- add missing build section
- fix URL

* Mon Dec 31 2012 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.4-1
- initial package generated by npm2rpm
